name: FE CI/CD - S3 only

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build FE
        working-directory: ./survey-fe
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: |
          npm ci
          echo "VITE_API_URL=$API_BASE_URL" > .env.production
          npm run build

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync ./survey-fe/dist s3://$S3_BUCKET --delete --cache-control max-age=31536000,public
          aws s3 cp ./survey-fe/dist/index.html s3://$S3_BUCKET/index.html --cache-control max-age=0,no-cache --metadata-directive REPLACE
